#!/usr/bin/env node
// Build the vendored ES modules the extension loads at runtime.
//
// MV3's CSP forbids loading scripts from a CDN, so Preact + htm must ship as
// local files. This copies them out of node_modules into vendor/ — vendor/ is a
// gitignored build artifact, regenerated by `npm install` (postinstall) or
// `npm run vendor`. Pinned versions live in package.json; `npm outdated` reports
// when newer ones are available.
//
// Only the modules actually imported by the extension are vendored (see
// lib/html.js). Both have relative/no imports, so this is a straight copy — no
// import rewriting needed.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const extDir = resolve(scriptDir, '..');
const vendorDir = resolve(extDir, 'vendor');
const modules = resolve(extDir, 'node_modules');

// source (in node_modules) -> destination filename (in vendor/)
const FILES = [
  ['preact/dist/preact.module.js', 'preact.module.js'],
  ['htm/dist/htm.module.js', 'htm.module.js'],
];

mkdirSync(vendorDir, { recursive: true });

for (const [src, dest] of FILES) {
  const from = resolve(modules, src);
  const to = resolve(vendorDir, dest);
  try {
    // Drop the trailing //# sourceMappingURL comment — we don't ship .map files,
    // so the reference would just dangle (and warns under vite/vitest).
    const code = readFileSync(from, 'utf8').replace(/\n?\/\/# sourceMappingURL=.*\s*$/, '\n');
    writeFileSync(to, code);
    console.log(`vendored ${dest}`);
  } catch (err) {
    console.error(`error: could not copy ${src} — is it installed? run 'npm install'`);
    console.error(err.message);
    process.exit(1);
  }
}

console.log(`\nDone. Vendor libs in ${vendorDir}/`);
console.log("Run 'npm outdated' to see if newer versions are available.");
