# Copy this file to config.dev.properties and set your dev OAuth client ID.
# See docs/android-development.md.

# Note this must be a WEB APPLICATION CLIENT ID, and not the ANDROID CLIENT ID.
# The ANDROID CLIENT ID isn't used in the code, it just says that android client can use the project. Very confusing

webClientId=YOUR_WEB_CLIENT_ID.apps.googleusercontent.com
